// Entry point
?start: element
?element: tag | tagend | string

////////////////////////////////////////////////////////////////////////////////
// TERMINALS
////////////////////////////////////////////////////////////////////////////////
NAMESPACE: ":"
TERMINATOR: "/"
WHITESPACE: /[ \t\n\f\r]+/
STRING: ESCAPED_STRING // FIXME: Match free-form strings without requiring double quotes around them.
AMBIGUOUSNUMBER: /[\da-f]+/i // In T2ML, whether or not the number is hex or decimal is contextual
NAMESPACEITEM: ("_"|LETTER|"-") ("_"|LETTER|"-")*
NAMESPACENAME: NAMESPACEITEM (WHITESPACE NAMESPACEITEM)*

////////////////////////////////////////////////////////////////////////////////
// Rules
////////////////////////////////////////////////////////////////////////////////

// Recurse until we're done processing elements
tag: "<" namespaces ">" element*
tagend: "<" "/" namespaces ">" element*
string: (STRING | WHITESPACE) element*

// Unlike HTML or XML, T2ML tags can look like: <font:univers condensed:25>
namespacecomponent: (NAMESPACENAME | AMBIGUOUSNUMBER)
namespaces: [namespacelist]
namespacelist: namespacecomponent (NAMESPACE namespacecomponent)*

////////////////////////////////////////////////////////////////////////////////
// Import common utilities.
////////////////////////////////////////////////////////////////////////////////

%import common.LETTER
%import common.NUMBER
%import common.CNAME -> NAME
%import common.ESCAPED_STRING
